# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    ENV["GITHUB_API_TOKEN"] = "74c88eaa932b8fd489db38b11fc5a426ae319564"
  end
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end

  desc "Submit pull request"
  lane :submit_feature do
    create_pull_request(
      repo: "iOSGeekster/testRepo",
      title: "Amazing new feature",
      base: "master", # optional, defaults to "master"
      body: "Please pull this in!" # optional
    )
  end

end
